### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by gnutix** [Ocramius/GeneratedHydrator#114]
Hi @Ocramius,

I've been [stuck](https://github.com/rectorphp/rector/issues/2417) in a [dependency](https://github.com/phpstan/phpstan/issues/2555) **hell** for [weeks](https://github.com/rectorphp/rector/pull/2373#issuecomment-562143782) between this package (which we use in our project) and PHPStan/Rector (common point: they all depend on `nikic/php-parser`, but different versions depending on the PHP version constraint). I've tried Docker'ing everything, using PHARs, and dark magic spells. But as our project is still on PHP 7.2 (and will be for some months - after all, EOL is 11.2020), nothing worked.

Then I looked up the history of this package and noticed that the version constraint was bumped from 7.2 to 7.3 in [this commit](https://github.com/Ocramius/GeneratedHydrator/commit/72462965143762d42afc714a225674e7a7a2caf3) from [this PR](https://github.com/Ocramius/GeneratedHydrator/pull/82). I've looked at the diff (and the one between `2.2.0` - compatible 7.2 - and `3.0` - requiring 7.3 -) and I can't for the sake of me find a **single change that requires** PHP 7.3. Which begs the question : why was the version constraint bumped in the first place ? (currently supposition : "because we can" ? ... :roll_eyes: )

If so, I'd like to make a point for all those who can't upgrade just yet and/or would hugely benefits using tools like Rector to do so. So, could we revert this constraint back to 7.2 ?

Thanks for your consideration - and hopefully your help getting me out of this nightmare.
gnutix

**Comment by Ocramius** [comment]
Heya!

I've read the pings on discussions pointing to this repo: I do bump dependency requirements regularly, even if no changes happen in the API, on purpose.

The rationale behind it is that I restrict the amount of dependency permutations to support, even at the cost of losing downstream users.

The next minor release will likely do the same again.

As mentioned elsewhere, if you need lower version constraints, use a fork and use composer's `"repository"` config to install from there.

To be clear: the correct resolution is to upgrade to 7.4 (now stable), and fix compatibility issues in your application.

**Comment by gnutix** [comment]
Fork it is then! Thanks for the complete answer, for clarity's sake (and maybe future wanderers...)
