### ISSUE TITLE
Guys! Slow down!

### ISSUE THREAD

**Issue by klynicol** [Ocramius/GeneratedHydrator#160]
I get wanting to implement the cool new features of PHP but how about a little backwards compatibility? I work with a company that JUST updated PHP to 7.2 (took months to migrate all the code with 3 programmers).

Going back into the commits and grabbing an older version I guess.

**Comment by Ocramius** [comment]
@klynicol last release is from [July 2020](https://github.com/Ocramius/GeneratedHydrator/releases/tag/4.0.0)?

Besides that, I also have clients that are on PHP 5.4: they just get older dependencies.

`^2.2.0` supports PHP 7.2 and newer:
 * https://github.com/Ocramius/GeneratedHydrator/releases/tag/2.2.0
 * https://github.com/Ocramius/GeneratedHydrator/blob/9b6b62db9959bec8fec88111e081e9456e36179f/composer.json#L22

**Comment by klynicol** [comment]
Got it thanks! I always try to avoid composer, maybe I should just cave.

**Comment by Ocramius** [comment]
`composer` is definitely the way to manage dependency updates, and that since 8 years - you should definitely try and look into it when you can :-)

If you fear using composer for **installation**, `nix` integration can make installation more stable: https://github.com/svanderburg/composer2nix
