### ISSUE TITLE
Current version (4.1.0) does not support php 7.4

### ISSUE THREAD

**Issue by zhsh0429** [Ocramius/GeneratedHydrator#261]
I got the following error message when I ran the example code in the PHP7.4 environment.

`ParseError : syntax error, unexpected '|', expecting ';' or '{'`

I think the reason is that it requires "ocramius/code-generator-utils": "^1.0.0" which requires "php": "^8.0",

**Comment by Ocramius** [comment]
The fact that you managed to install **this** repository with a PHP:^7.4
installation, and with code-generator-utils that requires PHP:^8, seems to
indicate that `--ignore-platform-reqs` was used: can you check the exact
versions of your dependencies?

**Comment by zhsh0429** [comment]
Hi Ocramius, thanks for your reply. Yes, you are right. I used the `--ignore-platform-reqs` flag. As a result, the version of code-generator-utils is 1.2.0. Since I have to use `--ignore-platform-reqs` flag. My current solution is to install code-generator-utils ~1.1.0 at first, and then install this package. I am not sure this is a good solution, but it could we for me. Thank you again for the fantastic work.

**Comment by Ocramius** [comment]
> I am not sure this is a good solution, but it could we for me.

I suggest trying to hunt down why you have to use that `--ignore-platform-reqs` in first place, and put effort in what's needed to get rid of it: that would avoid such problems in first place :)
