### ISSUE TITLE
Don't overwrite non-hydrated properties

### ISSUE THREAD

**Issue by sagikazarmark** [Ocramius/GeneratedHydrator#32]
Currently the hydrator overwrites every property in an object, even if they are not present in the data array. The hydrator shouldn't overwrite these properties.

**Comment by Ocramius** [comment]
@sagikazarmark the hydrator assumes that those properties exist in the initial array: this is an actual design decision

**Comment by sagikazarmark** [comment]
Does that mean when I hydrate the object it doesn't/cannot preserve anything from the previous state?

**Comment by sagikazarmark** [comment]
Here is the workaround:

``` php
            // UGLY WORKAROUND BEGINS
            $data = array_merge($hydrator->extract($entity), $data);
            // UGLY WORKAROUND ENDS

            $hydrator->hydrate($entity, $data);
```

It means that you have to populate your initial array with data like id, password, etc. which you probably don't update eg. using a form.

**Comment by Ocramius** [comment]
@sagikazarmark what could be done is generating an alternate hydrator that does these checks

**Comment by sagikazarmark** [comment]
Hm, I can see how it works. Thanks
