### ISSUE TITLE
Reflection speed

### ISSUE THREAD

**Issue by sagikazarmark** [Ocramius/GeneratedHydrator#33]
I am opening this issue just to make sure noone ever tries to do anything bad with the reflection part of generation.

I did some benchmarking as I liked the built-in filtering of reflection properties than filtering the array of them. Turned out it is much slower.

Benchmark (using athletic):

``` php
<?php

class Example extends \Athletic\AthleticEvent
{
    protected $class;

    public function setUp()
    {
        $this->class = new LongExampleWithValues;
    }

    /**
     * @iterations 1000
     */
    public function testBuiltInFiltering()
    {
        $reflection = new \ReflectionClass($this->class);

        $reflectionProperties = array_diff(
            $reflection->getProperties(\ReflectionProperty::IS_PUBLIC | \ReflectionProperty::IS_PROTECTED),
            $reflection->getProperties(\ReflectionProperty::IS_STATIC)
        );
    }

    /**
     * @iterations 1000
     */
    public function testArrayFiltering()
    {
        $reflection = new \ReflectionClass($this->class);

        $reflectionProperties = array_filter(
            $reflection->getProperties(),
            function (\ReflectionProperty $property) {
                return ($property->isPublic() || $property->isProtected()) && ! $property->isStatic();
            }
        );
    }
}
```

Test class:

``` php
<?php

class LongExampleWithValues
{
    private $a = 'a';
    protected $b = null;
    public $c = 1;
    static $d = true;

    public $e = -1;
    public $f = 'F';
    public $g = 1.0;
    public $h = -1.0;
    public $i = PHP_INT_MAX;
    public $j;
}
```

Results:

```
Example
    Method Name            Iterations    Average Time      Ops/second
    --------------------  ------------  --------------    -------------
    testBuiltInFiltering: [1,000     ] [0.0000722653866] [13,837.88349]
    testArrayFiltering  : [1,000     ] [0.0000248982906] [40,163.39976]
```

@Ocramius you are free to close this, just wanted to share some experience.

**Comment by sagikazarmark** [comment]
Hm, found an even faster way:

Benchmark:

``` php
...
    /**
     * @iterations 1000
     */
    public function testCombinedFiltering()
    {
        $reflection = new \ReflectionClass($this->class);

        $reflectionProperties = array_filter(
            $reflection->getProperties(\ReflectionProperty::IS_PUBLIC | \ReflectionProperty::IS_PROTECTED),
            function (\ReflectionProperty $property) {
                return ! $property->isStatic();
            }
        );
    }
...
```

New results:

```
    Method Name             Iterations    Average Time      Ops/second
    ---------------------  ------------  --------------    -------------
    testBuiltInFiltering : [1,000     ] [0.0000779654980] [12,826.18628]
    testArrayFiltering   : [1,000     ] [0.0000298421383] [33,509.66309]
    testCombinedFiltering: [1,000     ] [0.0000177173615] [56,441.81290]
```

**Comment by sagikazarmark** [comment]
Ah, I made a mistake: I included reflection initialization in the benchmark. Results slightly changed though:

```
    Method Name             Iterations    Average Time      Ops/second
    ---------------------  ------------  --------------    -------------
    testBuiltInFiltering : [1,000     ] [0.0000730552673] [13,688.26693]
    testArrayFiltering   : [1,000     ] [0.0000284912586] [35,098.48453]
    testCombinedFiltering: [1,000     ] [0.0000155844688] [64,166.44739]
```

**Comment by sagikazarmark** [comment]
The complete benchmark is available [here](https://github.com/indigophp/benchmarks/tree/master/benchmarks/Reflection/PropertyFiltering)

**Comment by Ocramius** [comment]
@sagikazarmark I'm not really understanding what you are testing here: I'd rather filter out the properties in a custom-generated hydrator instead, no?

**Comment by sagikazarmark** [comment]
@Ocramius sorry, I forgot to link the relevant code: https://github.com/Ocramius/GeneratedHydrator/blob/master/src/GeneratedHydrator/CodeGenerator/Visitor/HydratorMethodsVisitor.php#L218

**Comment by Ocramius** [comment]
Right, but what I suggested is implementing an additional pass that generates a new class with just properties from options left out.

#16 partially attempts to do that, but is incomplete: wanna give it a shot?

**Comment by sagikazarmark** [comment]
That is a completely different issue. I was just playing with reflection, speed, etc. and shared the result.

About the other issue: I actually realized why that decision was made and actually agree with it. I will look at the PR, but IMO it is impossible to generate a hydrator for all edge cases. So I will probably deal with....

**Comment by Ocramius** [comment]
> it is impossible to generate a hydrator for all edge cases

Obviously, but we can still generate various hydrators that cover most use-cases.

**Comment by Ocramius** [comment]
Closing as non-issue
