### ISSUE TITLE
Skipping undefined keys in the $data array

### ISSUE THREAD

**Issue by matthiasnoback** [Ocramius/GeneratedHydrator#36]
I've tried to use generated hydrators in my new project (https://github.com/matthiasnoback/broadway-serialization) but ran into a bit of trouble: when hydrating an object the data array needs to have a value for each property of the object. But in the case of, for example, event objects serialized and stored in an event store, some properties may have been added in the class of the event, but not in the data array. So an extra call to `array_key_exists()` would be required in this case.

Do you have any suggestions on how to fix this problem? I assume, based on other issues that have been reported, that you are not going to add any runtime checks. But if I want to, how should I proceed?

**Comment by Ocramius** [comment]
> So an extra call to array_key_exists() would be required in this case.

I'd rather `array_merge` with a extract + a hydrate (more efficient)

**Comment by matthiasnoback** [comment]
Ah, thanks, that sounds like a useful idea that I can test. 

For the record, I'll try something like this:

```php
$defaultData = $hydrator->extract($object);
$hydrator->hydrate(array_merge($defaultData, $data), $object);
```

**Comment by Ocramius** [comment]
Note that GeneratedHydrator is highly optimised to avoid method calls: anything else -> just a normal hydrator

**Comment by matthiasnoback** [comment]
I'll try how "bad" this is for the overall performance of the thing I'm writing.

**Comment by matthiasnoback** [comment]
I did some [benchmarking](https://github.com/matthiasnoback/broadway-serialization/blob/generated_hydrators/test/Performance/ReconstituteEvent.php) on this (see also the [hydrator class](https://github.com/matthiasnoback/broadway-serialization/blob/generated_hydrators/src/Hydration/HydrateUsingGeneratedHydrator.php)):

    Method Name                      Iterations    Average Time      Ops/second
    ------------------------------  ------------  --------------    -------------
    traditional_serialize         : [1,000     ] [0.0000034589767] [289,102.83981]
    traditional_deserialize       : [1,000     ] [0.0000045256615] [220,962.17469]
    reflection_serialize          : [1,000     ] [0.0000101439953] [98,580.48746]
    reflection_deserialize        : [1,000     ] [0.0000281500816] [35,523.87567]
    generated_hydrator_serialize  : [1,000     ] [0.0000130050182] [76,893.39469]
    generated_hydrator_deserialize: [1,000     ] [0.0000255374908] [39,158.11487]

It turns out that the generated hydrator is still faster than the [reflection-based one](https://github.com/matthiasnoback/broadway-serialization/blob/master/src/Hydration/HydrateUsingReflection.php), even though the difference isn't that big.

Do you have any suggestions on improving either of these hydrators for this particular use case?

**Comment by Ocramius** [comment]
> Do you have any suggestions on improving either of these hydrators for this particular use case?

Yes, generate a hydrator for the particular dataset that you have.

In order to get there, #16 must be finished first.

**Comment by matthiasnoback** [comment]
Thanks for pointing that out. I will revisit at some time in the future then, thanks for your help so far! You're free to close this if you like.

**Comment by Ocramius** [comment]
:+1:
