### ISSUE TITLE
Tag release allowing PHP 7 in Composer dependencies list

### ISSUE THREAD

**Issue by michaelmoussa** [Ocramius/GeneratedHydrator#41]

**Comment by michaelmoussa** [comment]
@Ocramius actually, looks like it's not going to be that easy. This causes a break in PHP 7 due to engine exceptions: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer.php#L72

```
<b>Fatal error</b>:  Uncaught ErrorException: Undefined variable: undefinedVariable in /Users/mmoussa/Code/tmp/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:70
```

**Comment by Ocramius** [comment]
@michaelmoussa about that comment on the parser error: still valid?

**Comment by michaelmoussa** [comment]
@Ocramius No. I deleted the comment because PEBCAK. I was trying to do too many things at once when I wrote that. :)

**Comment by ThaDafinser** [comment]
@Ocramius since PHP7 is stable, i think it's time for a release if possible.

**Comment by Ocramius** [comment]
@ThaDafinser doing that

**Comment by Ocramius** [comment]
Done via 1.2.0 :-)

**Comment by ThaDafinser** [comment]
Great. Thank you :tada:
