### ISSUE TITLE
Collections Hydration

### ISSUE THREAD

**Issue by YSimple** [Ocramius/GeneratedHydrator#45]
Hello Guys, i have a question about collection hydration, since my collections include other domain objects.

Lets say that i have `Car` Domain Model with has a collection of `Maintenance Logs` which include `Log`  Domain Model, and each has its own `Hydrator` when i call `CarHydrator->hydrate` will it use the `LogHydrator` automatically, or do i have to configure it in some way ?

**Comment by Ocramius** [comment]
You'd have to hydrate the collection first, then pass it to this hydrator as property value. The generated hydrator will not hydrate nested values.

**Comment by flowl** [comment]
What's the smartest way of hydrating the inner objects?
Should we pass the hydrator to the outer object and let it hydrate the inner object when the getter is used (lazy hydrating)?

Like:

```
class Car
{
    public function setLogsHydrator($hydrator) { ... }
    public function getLogs()
    {
        $logs = [];
        foreach ($this->logs as $log) {
            $logs[] = $this->logsHydrator->hydrate($log);
        }
        return $logs;
    }
}
```

**Comment by Ocramius** [comment]
Probably best to batch-recurse:

 1. first hydrate nesting level 3
 2. then hydrate nesting level 2 (including values from level 3)
 3. then hydrate nesting level 1 (including values from level 2)

If the issue is performance (this repository) then avoiding method calls is the best you can do.
