### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by sghinescu** [Ocramius/GeneratedHydrator#52]
I'm trying to install drupal using composer.
Here's an error I get:

Problem 1
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - Installation request for ocramius/generated-hydrator (locked at 1.1.1, required as ^1.1) -> satisfiable by ocramius/generated-hydrator[1.1.1].

**Comment by Ocramius** [comment]
2.0.0 works with PHP 7.x: https://github.com/Ocramius/GeneratedHydrator/blob/98a731e7d4e393513cb6f4e7f120da853680fb50/composer.json#L23
