### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by remicollet** [Ocramius/GeneratedHydrator#54]
With PHP 5.6, chicken and eggs issue:

Using 

    "require": {
        "zendframework/zendframework": "^3.0",
        "ocramius/generated-hydrator": "^2.0"
    },

    - ocramius/generated-hydrator 2.0.0 requires php ~7.0 -> your PHP version (5.6.23) does not satisfy that requirement.

Seems expected, so trying using previous version 

    "require": {
        "zendframework/zendframework": "^3.0",
        "ocramius/generated-hydrator": "^1.2"
    },

Can't be installed as requires zend-stdlib 2

**Comment by Ocramius** [comment]
Not maintaining 1.x besides security fixes, sorry...

This library is mostly to be required for performance reasons: consumers should upgrade to PHP 7.0 even before considering this library, I'd say.
