### ISSUE TITLE
Use `Closure::call` over `Closure::bind`

### ISSUE THREAD

**Issue by haampie** [Ocramius/GeneratedHydrator#57]
The current generated hydrator has the signature:

```php
class Example {
    private $a;
    protected $b;
    public $c;
}

class Generated extends Example implements HydratorInterface
{
    private $a = null;
    protected $b = null;
    public $c = null;
    function __construct()
    {
        $this->aWriter579676c837a6e801650765 = \Closure::bind(function ($object, $value) {
            $object->a = $value;
        }, null, 'Example');
    }
    function hydrate(array $data, $object)
    {
        $object->b = $data['b'];
        $object->c = $data['c'];
        $this->aWriter579676c837a6e801650765->__invoke($object, $data['a']);
        return $object;
    }

    // ... and extract()
}
```

But with PHP7 this can be simplified some :)

```php
class Generated extends Example implements HydratorInterface
{
    private $a = null;
    protected $b = null;
    public $c = null;
    function __construct()
    {
    }
    function hydrate(array $data, $object)
    {
        $object->b = $data['b'];
        $object->c = $data['c'];
        (function($data) {
            $object->a = $data['a'];
        })->call($object, $data);
        return $object;
    }

    // ... and extract()
}
```

`Closure::call` does not return a new closure like `Closure::bind` does, but simply temporarily binds it and immediately calls it. Some overhead is saved this way, and it is probably [faster](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.closure-call-method). Haven't tested it though, but wanted to mention it here anyway.

And isn't it an idea to wrap hydrate's body in a closure by default? Probably most of the time at least some data members are private.

```php
function hydrate(array $data, $object)
{
    (function($data) {
        $this->a = $data['a'];
        $this->b = $data['b'];
        $this->c = $data['c'];
    })->call($object, $data);
}
```

**Comment by Ocramius** [comment]
Defining the closure on `hydrate` is to be avoided, as it results in a new object instantiation, related garbage collection and generally a terrible performance impact.

**Comment by Ocramius** [comment]
Note: can still use `Closure::call()`, it just doesn't have any benefit without being able to define the scope of the call

**Comment by haampie** [comment]
Ah, you're right about the closure in hydrate() definition, stupid. 

Not sure what you mean by the last comment though, you can define the scope via the first argument of `call($scope, ...$args)`

Just FYI, some performance tests shows that `call` is as fast as `__invoke`, so that hydration is as fast as it was if you move the closures to the constructor.

Then I thought some performance could be gained in the constructor itself (if you're hydrating lots of different objects), but surprisingly it runs 15% slower than the current implementation.

See this gist: https://gist.github.com/haampie/f35d1623a07860c0440f4079a29ea316

Lastly I noted that some significant performance can be gained by reducing wrapping private setters in the same closure, reducing function calls; but I guess you already know that.

**Comment by Ocramius** [comment]
The problem is following:

```php
class A
{
    private $a;
}

class B extends A
{
}

// now hydrate this:
$b = new B();
```

In this scenario, `Closure::call()` will not work because we need to bind the closure to the scope of `A`.

If `Closure::call()` still has a performance over `__invoke()`, then we need to see the performance results from it. Ideally, we should first convert the performance tests to use phpbench (should be straightforward, not much to change).

**Comment by Ocramius** [comment]
> Lastly I noted that some significant performance can be gained by reducing wrapping private setters in the same closure, reducing function calls; but I guess you already know that.

Thought about that, but never got to actually build support for it
