### ISSUE TITLE
Compatibility with nikic/php-parser v3

### ISSUE THREAD

**Issue by kiler129** [Ocramius/GeneratedHydrator#67]
Hi @Ocramius,

Are you planning to upgrade `nikic/php-parser` dependency to use version 3? My project already uses `nikic/php-parser`, but requires version 3 which conflicts with version 2 used by `ocramius/generated-hydrator`.

**Comment by Ocramius** [comment]
You can send me a patch and I'll gladly merge/release

**Comment by pounard** [comment]
I still think that getting rid of this dependency would be a good idea :)

**Comment by Ocramius** [comment]
Why would I get rid of a dependency that I actually use explicitly?

**Comment by pounard** [comment]
From what I remember, and from the code I read and patched, it would be much more efficient in the end to just emit plain strings for the code, and simply use reflection to dig into object properties that need hydration; but I'm aware this would probably be a major change and subject to argument. But I think this dependency is like using a shotgun to kill a mosquito. I'm pro reducing the dependencies on such small library.

**Comment by Ocramius** [comment]
No, I'm not going to use string concatenation for this stuff.

I'm actually moving all my code generation libraries to AST-based code-generation and code analysis, as it is safer, more predictable, and even easier to test and discover language incompatibilities upfront.

Speed is also not an issue, but this is not runtime speed anyway.

**Comment by pounard** [comment]
If its versions hits conflicts with potential other components, I think this one too many, and the generated hydrator is a very small library, it could live without.

**Comment by Ocramius** [comment]
@pounard fork it then - I am *NOT* going into string-based codegen anyway. Or just bump the dependency, as I suggested above.

Dependency constraints are here to save our butt when things collide, so this sort of problem is fairly no

**Comment by pounard** [comment]
Hum, if generating code represents the most critical part of your library, you should not delegate it, it makes maintainance harder.

**Comment by Ocramius** [comment]
Look, I'm already maintaining https://github.com/Ocramius/ProxyManager/ and I know that string concatenation is the shittiest part of the entire stack, making failures,  tests, code transformation and so on harder to work with.

If I tell you that I don't want to go into string concatenation, then believe me: I won't go there. I already have a library doing that, and I don't want another one.

**Comment by pounard** [comment]
I understand your point of view, believe me, and I do take into consideration everything you're saying, I think it's interesting to think about it: it would reduce maybe by 50% or more this library code, and the need is much, much simpler than your proxy manager. And it probably will not evolve to something more complex. Maybe in fact it will evolve, but I can't ague this point because actually your need and your roadmap is very obscure.

As a matter of fact, I cannot just use this and continue to provide PR whenever I can if I can't rely on it in the future, I need a clearer view of what's going for this.

**Comment by Ocramius** [comment]
> And it probably will not evolve to something more complex

The initial plan for this lib was to just be an experiment to see whether we can make hydration ad UnitOfWork state comparisons in Doctrine ORM much much faster. We're not there yet, so I expect work to continue here (or as a new library, starting from this one) once I get back to actively doing OSS work for Doctrine Project.

I hope that gives you enough context about the future of this project. For now, it's mostly stashed on the side, as the functionality is pretty much complete for a prototype.

**Comment by pounard** [comment]
Thank you, once again, very much for your time. I hope you will decide soon about this library's future, it's promising and I crave for such library being stable and production ready.

**Comment by Ocramius** [comment]
It is tagged, therefore stable :-P

**Comment by gsdevme** [comment]
I believe this is now solved in master by #69

**Comment by Ocramius** [comment]
Thanks @gsdevme!

**Comment by kiler129** [comment]
Thanks @gsdevme & @Ocramius! 💯
